"""Make Paciente.edad nullable in database

Revision ID: 1919c834d782
Revises: 653defd60648
Create Date: 2025-05-11 17:34:38.840968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1919c834d782'
down_revision = '653defd60648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('edad',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('edad',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
