"""Add soft delete fields and explicit table names

Revision ID: 2292462b0158
Revises: a3fbf72ed379
Create Date: 2025-05-29 22:37:08.893324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2292462b0158'
down_revision = 'a3fbf72ed379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false'))) # <--- LÍNEA MODIFICADA
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cita_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('evolucion', schema=None) as batch_op:
        batch_op.drop_constraint('evolucion_paciente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'paciente', ['paciente_id'], ['id'])

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false'))) # <--- LÍNEA MODIFICADA
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_paciente_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['documento'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_paciente_is_deleted'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('evolucion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('evolucion_paciente_id_fkey', 'paciente', ['paciente_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cita_is_deleted'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
