"""Añadir relacion odontologo-paciente

Revision ID: 6fb3232c9745
Revises: 2292462b0158
Create Date: 2025-06-08 22:04:17.869645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb3232c9745'
down_revision = '2292462b0158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odontologo_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key(None, 'usuarios', ['odontologo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('odontologo_id')

    # ### end Alembic commands ###
