"""Add estado to Cita model

Revision ID: a3fbf72ed379
Revises: 69940c9b21af
Create Date: 2025-05-11 21:01:31.263164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fbf72ed379'
down_revision = '69940c9b21af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False, server_default='pendiente')) # <--- LÍNEA MODIFICADA
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
