"""Remove unique constraint from Paciente.email

Revision ID: f937ee2af072
Revises: 6fb3232c9745
Create Date: 2025-06-09 21:28:50.025732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f937ee2af072'
down_revision = '6fb3232c9745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint('paciente_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_unique_constraint('paciente_email_key', ['email'])

    # ### end Alembic commands ###
